// Code generated by "stringer -linecomment -type=gpu"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[amdGPU-0]
	_ = x[nvidiaGPU-1]
	_ = x[noGPU-2]
}

const _gpu_name = "AMDNvidiaCPU"

var _gpu_index = [...]uint8{0, 3, 9, 12}

func (i gpu) String() string {
	if i < 0 || i >= gpu(len(_gpu_index)-1) {
		return "gpu(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gpu_name[_gpu_index[i]:_gpu_index[i+1]]
}
