// Code generated by "stringer -linecomment -type=gpuModel"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[amdProductNavi10-0]
	_ = x[amdProductNavi21-1]
}

const _gpuModel_name = "Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]"

var _gpuModel_index = [...]uint8{0, 51, 93}

func (i gpuModel) String() string {
	if i < 0 || i >= gpuModel(len(_gpuModel_index)-1) {
		return "gpuModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gpuModel_name[_gpuModel_index[i]:_gpuModel_index[i+1]]
}
