// Code generated by "stringer -linecomment -type=ModelName"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Llama3-0]
	_ = x[CodeLlama-1]
	_ = x[CodeLlama13b-2]
	_ = x[CodeGemma-3]
	_ = x[DeepSeekCoder-4]
	_ = x[DeepSeekCoderV2-5]
	_ = x[Gemma-6]
	_ = x[Gemma2b-7]
	_ = x[Gemma2-8]
	_ = x[Llava-9]
	_ = x[Mistral-10]
	_ = x[Phi3-11]
}

const _ModelName_name = "llama3:latestcodellama:latestcodellama:13bcodegemma:7bdeepseek-coder:latestdeepseek-coder-v2:latestgemma:latestgemma:2bgemma2:latestllava:latestmistral:latestphi3:latest"

var _ModelName_index = [...]uint8{0, 13, 29, 42, 54, 75, 99, 111, 119, 132, 144, 158, 169}

func (i ModelName) String() string {
	if i < 0 || i >= ModelName(len(_ModelName_index)-1) {
		return "ModelName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModelName_name[_ModelName_index[i]:_ModelName_index[i+1]]
}
