// Code generated by "stringer -linecomment -type=ModelName"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BashBot-0]
	_ = x[CodeLlama-1]
	_ = x[CodeLlama13b-2]
	_ = x[Gemma-3]
	_ = x[Llama3-4]
}

const _ModelName_name = "bashbot:latestcodellama:latestcodellama:13bgemma:latestllama3:latest"

var _ModelName_index = [...]uint8{0, 14, 30, 43, 55, 68}

func (i ModelName) String() string {
	if i < 0 || i >= ModelName(len(_ModelName_index)-1) {
		return "ModelName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModelName_name[_ModelName_index[i]:_ModelName_index[i+1]]
}
