// Code generated by "stringer -linecomment -type=processingDevice"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[amdGPU-0]
	_ = x[nvidiaGPU-1]
	_ = x[noGPU-2]
}

const _processingDevice_name = "AMDNvidiaCPU"

var _processingDevice_index = [...]uint8{0, 3, 9, 12}

func (i processingDevice) String() string {
	if i < 0 || i >= processingDevice(len(_processingDevice_index)-1) {
		return "processingDevice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _processingDevice_name[_processingDevice_index[i]:_processingDevice_index[i+1]]
}
