// Code generated by "stringer -linecomment -type=PromptMsg"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CorrectGrammar-0]
	_ = x[TryAgain-1]
	_ = x[MakeItAList-2]
	_ = x[MakeItFriendly-3]
	_ = x[MakeItFriendlyRedo-4]
	_ = x[MakeItProfessional-5]
}

const _PromptMsg_name = "Correct GrammarTryAgainMakeItAListMake it FriendlyMake it FriendlyMake it Professional"

var _PromptMsg_index = [...]uint8{0, 15, 23, 34, 50, 66, 86}

func (i PromptMsg) String() string {
	if i < 0 || i >= PromptMsg(len(_PromptMsg_index)-1) {
		return "PromptMsg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PromptMsg_name[_PromptMsg_index[i]:_PromptMsg_index[i+1]]
}
