name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: bug
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Include information to reproduce the behavior such as:
        * What program was running when the bug occurred?
        * What text was being processed?
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: Include information to reproduce the behavior.
  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add a screenshot of the Ctrl+Revise main window showing the settings.
        This will tell us what settings are enabled and disabled and which AI model is in use.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add a screenshot of the Ctrl+Revise main window showing the settings.
  - type: markdown
    attributes:
      value: |
        **Desktop (please complete the following information):**
        - OS: \[e.g. Windows, MacOS, Linux\]
        - Version \[e.g. 22\] Can be found in the about window.
  - type: input
    id: desktop_info
    attributes:
      label: Desktop information
      description: Provide OS and version information.
  - type: markdown
    attributes:
      value: |
        **Logs**
        If applicable, add logs.
        If started from a command line, copy the output. If started from a desktop, Ctrl+Revise logs can be found in the system log viewer.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs.
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.